# ? ??????? ?????? ???????
spring.application.name=messenger

# ? 1. ????????? ????? ?????????? ???????? ???? ?????? localhost
spring.datasource.url=jdbc:postgresql://amvera-spinastya-cnpg-elis-db-rw:5432/Elismessenger

# ? 2. ????? ??? ?????? ?????????? ???????????? (?? ??????? Suan ? ??????? ?????!)
spring.datasource.username=${DB_USERNAME}

# ? 3. ?????? ??????, ??????? ?? ?????? ??? ??????? ? ??? ???? (? ???????? ?????? ?? ????)
spring.datasource.password=${DB_PASSWORD}

# ????????? ?????????????? ???????? ?????? Hibernate, ????? ?? ??? ??? ????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


